version: '2.1'

volumes:
  hackthebox:

services:
  playground:
    build: .
    image: fphammerle/hackthebox-playground
    volumes:
    - hackthebox:/hackthebox
    devices:
    - /dev/net/tun
    cap_add:
    - NET_ADMIN
    # https://github.com/dperson/openvpn-client/issues/75
    sysctls:
    - net.ipv6.conf.all.disable_ipv6=0

# https://docs.docker.com/compose/compose-file/compose-file-v2/
